name: "Continuous build (FreeBSD)"

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'continuous*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            dependencies: automake bash cmake gcc git gmake libtool meson nasm perl5 pkgconf python sudo wget wine yasm zip

          - os: ubuntu-latest
            arch: aarch64
            dependencies: automake bash cmake gcc git gmake libtool meson nasm perl5 pkgconf python sudo wget yasm zip

      fail-fast: false

    runs-on: ${{ matrix.os }}

    env:
      AppImageArch: ${{ matrix.arch }}
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Free up space
        run: |
          rm -fr boca/system-*

      - name: Start VM
        id: vm
        uses: vmactions/freebsd-vm@v1
        with:
          release: "13.5"
          arch: ${{ matrix.arch }}
          envs: 'AppImageArch RELEASE_TOKEN'
          sync: sshfs

      - name: Enable Linux support
        shell: freebsd {0}
        run: |
          sysrc linux_enable="YES"
          service linux start

      - name: Install dependencies
        shell: freebsd {0}
        run: |
          pkg update
          pkg install -y ${{ matrix.dependencies }}
          pkg install -y gnome-icon-theme gtk3

      - name: Build AppImage
        shell: freebsd {0}
        run: |
          pw user add -n vmuser -m -g wheel
          echo "vmuser ALL=(ALL) NOPASSWD: ALL" >> /usr/local/etc/sudoers
          cp -R $GITHUB_WORKSPACE .
          chown -R vmuser freac
          cd freac
          su vmuser -c .github/workflows/tools/build-appimage
