name: "Verify build"

on:
  push:
    branches-ignore:
      - i18n-master
  pull_request:
    branches-ignore:
      - i18n-master
  schedule:
    - cron: '0 6 * * 1'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cc: gcc
            cxx: g++

          - os: ubuntu-latest
            cc: clang
            cxx: clang++

          - os: macos-latest
            cc: clang
            cxx: clang++

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install smooth dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt update
          sudo apt install -y libbz2-dev libcurl4-openssl-dev libfribidi-dev libgtk-3-dev libjpeg-dev libxml2-dev

      - name: Checkout smooth
        uses: actions/checkout@v2
        with:
          repository: enzo1982/smooth
          path: smooth

      - name: Build smooth
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: |
          cd smooth
          make -j$(nproc)
          sudo make install prefix=/usr/local
          cd ..

      - name: Install BoCA dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt update
          sudo apt install -y libcdio-dev libcdio-paranoia-dev libexpat1-dev liburiparser-dev libpulse-dev

      - name: Install BoCA dependencies macOS
        if: ${{ runner.os == 'macOS' }}
        run: |
          wget https://ftp.gnu.org/gnu/libcdio/libcdio-2.1.0.tar.bz2
          tar xfj libcdio-2.1.0.tar.bz2
          cd libcdio-2.1.0
          ./configure --prefix=/usr/local && make -j$(nproc) && sudo make install
          cd ..
          wget https://ftp.gnu.org/gnu/libcdio/libcdio-paranoia-10.2+2.0.1.tar.bz2
          tar xfj libcdio-paranoia-10.2+2.0.1.tar.bz2
          cd libcdio-paranoia-10.2+2.0.1
          sed -i -e "s/-Wl,--version-script=.*\.la\.ver//" lib/*/Makefile.in
          ./configure --prefix=/usr/local && make -j$(nproc) && sudo make install
          cd ..

      - name: Checkout BoCA
        uses: actions/checkout@v2
        with:
          repository: enzo1982/BoCA
          path: boca

      - name: Build BoCA
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: |
          cd boca
          make -j$(nproc)
          sudo make install prefix=/usr/local
          cd ..

      - name: Install dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt update
          sudo apt install -y libudev-dev

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

      # If this run was triggered by a pull request event, then checkout
      # the head of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      
      - name: Build
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: |
          make -j$(nproc)
